name: Auto Tag and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: v0.0.0

      - name: Generate next version
        id: next_version
        run: |
          CURRENT_VERSION=${{ steps.get_latest_tag.outputs.tag }}
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}"
          echo "version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.next_version.outputs.version }}'
          name: '${{ steps.next_version.outputs.version }}'
          draft: false
          prerelease: false
