# example 1: on push to master
name: 下载文档并发布
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: output
          key: "cache-key"
      - name: Autotag
        uses: phish108/autotag-action@v1.1.64
        id: autotag
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: 'true'
      # - name: Set Up Golang Environment
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: 1.20.4


      - name: 准备环境
        run: |
          echo ${{ steps.autotag.outputs.tag }}
          echo ${{ steps.autotag.outputs.new-tag }}
          sudo apt update
          sudo apt install ttf-wqy-zenhei
          fc-cache -f -v
      - name: download doc
        run: |
          # ./doc2pdf
          mkdir -p dist
          echo ${{ steps.autotag.outputs.new-tag }} > dist/tag.txt
          ls -la
          ls -la dist

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.autotag.outputs.new-tag }}"
          name: "v${{ steps.autotag.outputs.new-tag }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["dist/*"]'
