# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout Github Code
      uses: actions/checkout@v3

    - name: Autotag
      uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        with-v: "true"